name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - 
      uses: actions/checkout@v4
    - 
      name: Copy env
      run: cp .env.dist .env
    - 
      name: Start containers
      run: docker compose up -d --build
    - 
      name: Stop containers
      if: always()
      run: docker compose down